services:
  - type: web
    name: telegram-forward-bot
    env: python
    plan: free
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11
